"""Tests for write_jira_children.py.

Covers parsing, validation, the 4-phase action emission ordering, link
directionality, idempotency at the parse layer, and goldens.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import write_jira_children as wjc

# ----- helpers -----


def _subtask_actions(actions: list[dict]) -> list[dict]:
    """Phase-2 ceremony Sub-task actions.

    `atlassian.createJiraSubtask` doesn't exist on the MCP — the action plan
    emits `atlassian.createJiraIssue` with `issueType="Sub-task"` and a
    top-level `parent` field instead.
    """
    return [
        a
        for a in actions
        if a["tool"] == "atlassian.createJiraIssue"
        and a["args"].get("issueType") == "Sub-task"
    ]


def _slice_create_actions(actions: list[dict]) -> list[dict]:
    """Phase-1 slice-creation actions (everything that is NOT a Sub-task)."""
    return [
        a
        for a in actions
        if a["tool"] == "atlassian.createJiraIssue"
        and a["args"].get("issueType") != "Sub-task"
    ]


def _slice_block(
    letter: str,
    *,
    type_: str = "Task",
    title: str | None = None,
    component: str = "payment-platform",
    depends_on: str = "(none)",
    description: str | None = None,
    modules: str = "Foo, Bar",
    user_stories: str = "1, 2",
    oneliner: str = "do the thing",
) -> str:
    title = title or f"[BE] Slice {letter}"
    description = description or (
        "## What to build (in payment-platform)\n\n"
        "Do the thing.\n\n"
        "## Acceptance criteria\n\n"
        "- [ ] does X\n- [ ] does Y\n"
    )
    indented = "\n".join("  " + line for line in description.splitlines())
    return (
        f"## Slice {letter} — {component}: {oneliner}\n"
        f"- type: {type_}\n"
        f"- title: {title}\n"
        f"- component: {component}\n"
        f"- depends_on: {depends_on}\n"
        f"- modules: {modules}\n"
        f"- user_stories: {user_stories}\n"
        f"- description: |\n{indented}\n"
    )


def _plan_doc(*slice_blocks: str, parent_key: str = "PLTPM-99001") -> str:
    return (
        f"# Slice plan for {parent_key}: test plan\n\n"
        f"> Generated by propose_slices.py from {parent_key} + graphify on 2026-05-02T16:59Z.\n\n"
        + "\n".join(slice_blocks)
    )


# ----- parsing -----


class TestParse:
    def test_parses_single_slice(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        assert len(slices) == 1
        s = slices[0]
        assert s["letter"] == "A"
        assert s["type"] == "Task"
        assert s["component"] == "payment-platform"
        assert s["depends_on"] == "(none)"
        assert "Acceptance criteria" in s["description"]

    def test_parses_multiple_slices_in_letter_order(self):
        doc = _plan_doc(
            _slice_block("B", oneliner="b"),
            _slice_block("A", oneliner="a"),
            _slice_block("C", oneliner="c"),
        )
        slices = wjc.parse_slice_plan(doc)
        assert [s["letter"] for s in slices] == ["A", "B", "C"]

    def test_ignores_non_slice_h2_sections(self):
        doc = (
            "# title\n\n"
            "## Notes\n\nirrelevant.\n\n" + _slice_block("A")
        )
        slices = wjc.parse_slice_plan(doc)
        assert len(slices) == 1

    def test_empty_doc_returns_empty_list(self):
        assert wjc.parse_slice_plan("") == []

    def test_parses_depends_on_list(self):
        doc = _plan_doc(_slice_block("A"), _slice_block("B", depends_on="A"))
        slices = wjc.parse_slice_plan(doc)
        # depends_on stays as raw string at parse time; parse_depends_on splits it.
        assert wjc.parse_depends_on(slices[1]["depends_on"]) == ["A"]


class TestParseDependsOn:
    def test_none_literal(self):
        assert wjc.parse_depends_on("(none)") == []

    def test_empty(self):
        assert wjc.parse_depends_on("") == []

    def test_single_letter(self):
        assert wjc.parse_depends_on("A") == ["A"]

    def test_comma_separated(self):
        assert wjc.parse_depends_on("A, B, C") == ["A", "B", "C"]

    def test_strips_whitespace(self):
        assert wjc.parse_depends_on("  A , B  ") == ["A", "B"]


# ----- validation -----


class TestValidate:
    def test_happy_path_passes(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        wjc.validate_slices(slices, "PLTPM-99001")

    def test_rejects_empty_plan(self):
        with pytest.raises(wjc.InvalidSlicePlan, match="no slices"):
            wjc.validate_slices([], "PLTPM-99001")

    def test_rejects_missing_required_key(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        del slices[0]["component"]
        with pytest.raises(wjc.InvalidSlicePlan, match="missing required key `component`"):
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_rejects_unknown_type(self):
        doc = _plan_doc(_slice_block("A", type_="Bug"))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan, match="type 'Bug'"):
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_accepts_research_either_form(self):
        # parse_keyvalue_block strips trailing whitespace; we accept both `Research`
        # and `Research ` from PM/eng input. Trailing space is re-applied at emit time.
        for form in ("Research", "Research "):
            doc = _plan_doc(_slice_block("A", type_=form))
            slices = wjc.parse_slice_plan(doc)
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_accepts_design_either_form(self):
        for form in ("Design", "Design "):
            doc = _plan_doc(_slice_block("A", type_=form))
            slices = wjc.parse_slice_plan(doc)
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_rejects_non_canonical_component(self):
        doc = _plan_doc(_slice_block("A", component="random-repo"))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan, match="not in canonical"):
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_rejects_unresolved_depends_on(self):
        doc = _plan_doc(_slice_block("A", depends_on="Z"))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan, match="unknown slice 'Z'"):
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_rejects_self_dependency(self):
        doc = _plan_doc(_slice_block("A", depends_on="A"))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan, match="cannot reference itself"):
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_rejects_TODO_in_description(self):
        bad_desc = (
            "## What to build\n\nDo X.\n\n"
            "## Acceptance criteria\n\n"
            "<!-- TODO: PM/eng must fill in -->\n- [ ] criterion\n"
        )
        doc = _plan_doc(_slice_block("A", description=bad_desc))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan, match="literal `TODO`"):
            wjc.validate_slices(slices, "PLTPM-99001")

    def test_aggregates_multiple_failures(self):
        bad_desc = "stuff\nTODO here\n"
        doc = _plan_doc(_slice_block("A", type_="Bug", component="x", description=bad_desc))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan) as exc:
            wjc.validate_slices(slices, "PLTPM-99001")
        msg = str(exc.value)
        assert "type 'Bug'" in msg
        assert "not in canonical" in msg
        assert "literal `TODO`" in msg

    def test_rejects_empty_parent_key(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        with pytest.raises(wjc.InvalidSlicePlan, match="parent_key is empty"):
            wjc.validate_slices(slices, "")


# ----- action emission -----


class TestEmitActions:
    def test_phase1_create_issue_per_slice_in_letter_order(self):
        doc = _plan_doc(_slice_block("A"), _slice_block("B"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")

        create_issues = _slice_create_actions(actions)
        assert len(create_issues) == 2
        assert create_issues[0]["stores_as"] == "slice_A_key"
        assert create_issues[1]["stores_as"] == "slice_B_key"
        assert create_issues[0]["args"]["projectKey"] == "PLTPM"
        assert create_issues[0]["args"]["issueType"] == "Task"
        assert create_issues[0]["args"]["components"] == [{"name": "payment-platform"}]

    def test_phase2_emits_5_subtasks_per_task(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")

        subtasks = _subtask_actions(actions)
        assert len(subtasks) == 5
        names = [a["args"]["summary"] for a in subtasks]
        assert names == [
            "Development",
            "Code Review 1",
            "Code Review 2",
            "Test case creation",
            "Test case execution",
        ]
        assert all(a["args"]["description"] == "" for a in subtasks)
        assert all(a["args"]["parent"] == "{{slice_A_key}}" for a in subtasks)
        assert all(a["args"]["projectKey"] == "PLTPM" for a in subtasks)
        assert all(a["args"]["issueType"] == "Sub-task" for a in subtasks)
        assert all(a["tool"] == "atlassian.createJiraIssue" for a in subtasks)

    def test_phase2_never_emits_nonexistent_createJiraSubtask_tool(self):
        """createJiraSubtask doesn't exist on the Atlassian MCP. Regression for F1 friction 9."""
        doc = _plan_doc(_slice_block("A"), _slice_block("B"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        assert all(a["tool"] != "atlassian.createJiraSubtask" for a in actions)

    def test_phase2_skips_subtasks_for_research_slice(self):
        doc = _plan_doc(_slice_block("A", type_="Research"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")

        assert _subtask_actions(actions) == []

    def test_phase2_skips_subtasks_for_design_slice(self):
        doc = _plan_doc(_slice_block("A", type_="Design"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        assert _subtask_actions(actions) == []

    def test_emits_trailing_space_for_research_in_action_plan(self):
        doc = _plan_doc(_slice_block("A", type_="Research"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        create = _slice_create_actions(actions)[0]
        assert create["args"]["issueType"] == "Research "

    def test_emits_trailing_space_for_design_in_action_plan(self):
        doc = _plan_doc(_slice_block("A", type_="Design"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        create = _slice_create_actions(actions)[0]
        assert create["args"]["issueType"] == "Design "

    def test_does_not_append_trailing_space_for_task(self):
        doc = _plan_doc(_slice_block("A", type_="Task"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        create = _slice_create_actions(actions)[0]
        assert create["args"]["issueType"] == "Task"

    def test_phase2_emits_subtasks_for_technical_story(self):
        doc = _plan_doc(_slice_block("A", type_="Technical Story"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        assert len(_subtask_actions(actions)) == 5

    def test_phase3_implement_link_parent_to_each_child(self):
        doc = _plan_doc(_slice_block("A"), _slice_block("B"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")

        implement_links = [
            a for a in actions
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Implement"
        ]
        assert len(implement_links) == 2
        assert all(a["args"]["inwardIssue"] == "PLTPM-99001" for a in implement_links)
        out_keys = sorted(a["args"]["outwardIssue"] for a in implement_links)
        assert out_keys == ["{{slice_A_key}}", "{{slice_B_key}}"]

    def test_phase4_is_blocked_by_directionality(self):
        # B depends on A → A blocks B. inwardIssue=A (blocker), outwardIssue=B (blocked).
        doc = _plan_doc(_slice_block("A"), _slice_block("B", depends_on="A"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        blocks = [
            a for a in actions
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Blocks"
        ]
        assert len(blocks) == 1
        assert blocks[0]["args"]["inwardIssue"] == "{{slice_A_key}}"
        assert blocks[0]["args"]["outwardIssue"] == "{{slice_B_key}}"

    def test_phase4_handles_multiple_depends_on(self):
        doc = _plan_doc(
            _slice_block("A"),
            _slice_block("B"),
            _slice_block("C", depends_on="A, B"),
        )
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        blocks = [
            a for a in actions
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Blocks"
        ]
        assert len(blocks) == 2
        in_letters = sorted(a["args"]["inwardIssue"] for a in blocks)
        assert in_letters == ["{{slice_A_key}}", "{{slice_B_key}}"]
        assert all(a["args"]["outwardIssue"] == "{{slice_C_key}}" for a in blocks)

    def test_phase4_no_blocks_when_no_depends_on(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        blocks = [
            a for a in actions
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Blocks"
        ]
        assert blocks == []

    def test_4_phase_ordering(self):
        # createIssue → subtasks → Implement → Blocks
        doc = _plan_doc(_slice_block("A"), _slice_block("B", depends_on="A"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")

        is_slice_create = {id(a) for a in _slice_create_actions(actions)}
        is_subtask = {id(a) for a in _subtask_actions(actions)}
        last_create_issue = max(i for i, a in enumerate(actions) if id(a) in is_slice_create)
        first_subtask = min(i for i, a in enumerate(actions) if id(a) in is_subtask)
        last_subtask = max(i for i, a in enumerate(actions) if id(a) in is_subtask)
        first_implement = min(
            i for i, a in enumerate(actions)
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Implement"
        )
        last_implement = max(
            i for i, a in enumerate(actions)
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Implement"
        )
        first_blocks = min(
            i for i, a in enumerate(actions)
            if a["tool"] == "atlassian.createIssueLink" and a["args"]["type"] == "Blocks"
        )

        assert last_create_issue < first_subtask
        assert last_subtask < first_implement
        assert last_implement < first_blocks

    def test_steps_are_consecutive_and_one_indexed(self):
        doc = _plan_doc(_slice_block("A"))
        slices = wjc.parse_slice_plan(doc)
        actions = wjc.emit_actions(slices, "PLTPM-99001")
        steps = [a["step"] for a in actions]
        assert steps == list(range(1, len(actions) + 1))


# ----- idempotency at parse layer -----


class TestIdempotency:
    def test_same_input_byte_identical_output(self):
        doc = _plan_doc(
            _slice_block("A"),
            _slice_block("B", depends_on="A"),
        )
        slices1 = wjc.parse_slice_plan(doc)
        slices2 = wjc.parse_slice_plan(doc)
        plan1 = wjc.build_plan(slices1, "PLTPM-99001")
        plan2 = wjc.build_plan(slices2, "PLTPM-99001")
        assert json.dumps(plan1, sort_keys=True) == json.dumps(plan2, sort_keys=True)


# ----- CLI -----


class TestCLI:
    def test_happy_path_emits_full_plan(self, tmp_path: Path, run_main):
        doc = _plan_doc(_slice_block("A"))
        plan_path = tmp_path / "PLTPM-99001.md"
        plan_path.write_text(doc, encoding="utf-8")

        code, out, err = run_main(
            wjc.main,
            "--slice-plan",
            str(plan_path),
            "--parent-key",
            "PLTPM-99001",
        )
        assert code == 0
        assert err == ""
        assert out["status"] == "ok"
        assert out["slice_count"] == 1
        assert out["letters"] == ["A"]
        # Spot-check phase 1 + 3 emitted.
        tools = {a["tool"] for a in out["actions"]}
        assert "atlassian.createJiraIssue" in tools
        assert "atlassian.createIssueLink" in tools

    def test_invalid_plan_returns_code_1(self, tmp_path: Path, run_main):
        bad_desc = "## Acceptance criteria\n<!-- TODO -->\n"
        doc = _plan_doc(_slice_block("A", description=bad_desc))
        plan_path = tmp_path / "bad.md"
        plan_path.write_text(doc, encoding="utf-8")
        code, out, _ = run_main(
            wjc.main,
            "--slice-plan",
            str(plan_path),
            "--parent-key",
            "PLTPM-99001",
        )
        assert code == 1
        assert out["status"] == "invalid"
        assert "TODO" in out["reason"]

    def test_missing_file_returns_code_2(self, tmp_path: Path, run_main):
        code, _, err = run_main(
            wjc.main,
            "--slice-plan",
            str(tmp_path / "missing.md"),
            "--parent-key",
            "PLTPM-99001",
        )
        assert code == 2
        assert err


# ----- goldens -----


@pytest.mark.parametrize(
    "name,parent_key",
    [
        ("merchant-health", "PLTPM-99001"),
        ("transfers-v3", "PLTPM-99002"),
    ],
)
class TestActionPlanGoldens:
    """Lock the write_jira_children output for the two reference redlined plans.

    To update: run write_jira_children.py manually against
    `slice-plan-<name>-redlined.md` and replace `<name>.expected.json`.
    """

    def test_action_plan_byte_identical_to_golden(
        self, fixtures_dir: Path, name: str, parent_key: str, run_main
    ):
        plan_path = fixtures_dir / f"slice-plan-{name}-redlined.md"
        expected_path = fixtures_dir / f"{name}.expected.json"

        code, out, _ = run_main(
            wjc.main,
            "--slice-plan",
            str(plan_path),
            "--parent-key",
            parent_key,
        )
        assert code == 0
        actual_text = json.dumps(out, indent=2, ensure_ascii=False) + "\n"
        expected_text = expected_path.read_text(encoding="utf-8")
        assert actual_text == expected_text, (
            f"action plan for {name} drifted from {expected_path}. Regenerate "
            "the fixture if the change is intentional: "
            f"`python write_jira_children.py --slice-plan {plan_path.name} "
            f"--parent-key {parent_key} > tests/fixtures/{name}.expected.json`."
        )
